#!/bin/bash
cd /home/ubuntu/

# use systemd to start and monitor dotnet application
systemctl enable kestrel-migratedVisitorCounter.service
systemctl start kestrel-migratedVisitorCounter.service

# start apache
systemctl restart apache2.service